### ISSUE TITLE
Docker image incompatible with arm64

### ISSUE THREAD

**Issue by maantje** [buggregator/server#106]
The latest Docker image of the Buggregator server is incompatible with arm64 machines.

## Steps to reproduce

- Get an arm64 machine (I am testing this on a cax11 server at Hetzner).
- Install Docker.
- `docker pull ghcr.io/buggregator/server:latest`
- `docker run ghcr.io/buggregator/server:latest`

```
exec /usr/local/bin/docker-php-entrypoint: exec format error
```

## Additional information

Docker inspect shows the correct `arm64` architecture for the image. I did some digging and found the issue is not with the Buggregator server directly, but with the images from the repositories the server depends on.

`ghcr.io/buggregator/frontend:latest` gives me `"Architecture": "amd64"`.
`ghcr.io/buggregator/docker:latest` also gives me `"Architecture": "amd64"`.

## Workaround

For now, I cloned the Buggregator server, docker, and frontend repositories. Then, I built my own arm64 images for frontend and docker, pushed them to `ghcr.io`, and edited the Dockerfile of the Buggregator server to use my images.

I built an arm64 image of the server and pushed that to `ghcr.io` as well.

I made the final image of the server public in case someone else needs it for now.

`docker pull ghcr.io/maantje/buggregator:latest`

**Comment by butschster** [comment]
Hi @maantje,

It would be greatly beneficial to the community if you could share your changes. I encourage you to create a Pull Request with the modifications you made.

Your contribution would be a valuable addition to the project. Looking forward to seeing your PR!

Thx!

**Comment by butschster** [comment]
Hi @maantje! I added both amd64 and arm64 platforms for the frontend and docker repositories. It would be great if you tried Buggregator v 1.3.0 to check if everything is ok.

**Comment by maantje** [comment]
Hi @butschster,

Thank you for the new release! I just gave it a try, and it seems all good! I also noticed Sentry reports are now coming through as well; I couldn't get them to work before.

**Comment by butschster** [comment]
@maantje 
Thx for the feedback! 

> I also noticed Sentry reports are now coming through as well; I couldn't get them to work before.

Yeah, at last, I found some time to cover the handlers with feature tests, and it helped to fix the issues.
