### ISSUE TITLE
Replace KV storage with surrealdb

### ISSUE THREAD

**Issue by butschster** [buggregator/server#114]
We need to find an alternative to the current key-value (KV) storage system used in Bugregator for managing events and settings. One potential replacement is SurrealDB, an in-memory database. It's essential to investigate SurrealDB to determine its feasibility as a substitute for our existing KV storage solution. Relevant information can be found at https://github.com/surrealdb/surrealdb.

**Comment by butschster** [comment]
> When I mentioned [SurrealDB](https://surrealdb.com/) to you, I meant that [LIVE SELECT](https://docs.surrealdb.com/docs/surrealql/statements/live-select) can replace data propagation via WebSocket (supposedly the same, but different). Is this what you need?

I need some persistent storage inside container. And there are two options: SurrealDB or Postgres.

**Comment by roxblnfk** [comment]
https://github.com/dolthub/dolt
