### ISSUE TITLE
Include Syntax Highlighting Language Option in Var-Dumper Dumps

### ISSUE THREAD

**Issue by butschster** [buggregator/server#164]
We aim to enhance Var-Dumper by allowing developers to specify the language for syntax highlighting within their dumps. This enhancement will streamline the debugging process and improve the readability of dumped content, particularly in cases involving multiple programming languages.

Introduce a new parameter or method within Var-Dumper that enables developers to specify the language for syntax highlighting. This parameter could accept standard language identifiers or aliases, such as those commonly used in code editors or highlighting libraries (e.g., "php", "javascript", "python", etc.).

![image](https://github.com/buggregator/server/assets/773481/b98badec-42d9-43af-a3d6-ca936f8141d8)

The current method for adding additional context to a VarDumper involves complex and verbose code, which can be cumbersome and error-prone. This proposal aims to enhance the Symfony VarDumper API to provide a more intuitive and concise way of adding context information.

```php
<?php

use Symfony\Component\VarDumper\Caster\ReflectionCaster;
use Symfony\Component\VarDumper\Cloner\VarCloner;
use Symfony\Component\VarDumper\Dumper\ContextProvider\CliContextProvider;
use Symfony\Component\VarDumper\Dumper\ContextProvider\SourceContextProvider;
use Symfony\Component\VarDumper\Dumper\ContextualizedDumper;
use Symfony\Component\VarDumper\Dumper\HtmlDumper;
use Symfony\Component\VarDumper\Dumper\ServerDumper;

\Symfony\Component\VarDumper\VarDumper::setHandler(function ($var, ?string $label = null) {
    $dumper = new ServerDumper('127.0.0.1', new HtmlDumper(), [
        'language' => 'php', // <===== this is the line that you need to add to your code
        'cli' => new CliContextProvider(),
        'source' => new SourceContextProvider(),
    ]);
    $dumper = new ContextualizedDumper($dumper, [new SourceContextProvider()]);


    $cloner = new VarCloner();
    $cloner->addCasters(ReflectionCaster::UNSET_CLOSURE_FILE_INFO);
    $var = $cloner->cloneVar($var);

    if (null !== $label) {
        $var = $var->withContext(['label' => $label]);
    }

    $dumper->dump($var);
});
```

**Proposed Solutions:**

1. **Static Method in VarDumper Class:** Introduce a static method in the `VarDumper` class, such as `addContext()`, which accepts an array of default context settings. Developers can then call this method to set default context options, including the language for syntax highlighting. See https://github.com/symfony/var-dumper/blob/7.0/VarDumper.php#L101

```php
\Symfony\Component\VarDumper\VarDumper::addContext(['language' => 'php']);
```

2. **Named Argument in `dump()` function:** Extend the `dump()` function to accept a named argument `context`, allowing developers to specify default context settings directly when calling `dump()`.

```php
dump($foo, $bar, ..., context: ['language' => 'php']);
```

UPD: as I can see there is a PR in symfony repository https://github.com/symfony/symfony/pull/48667 that can solve our problem.

**Comment by roxblnfk** [comment]
Using trap the user may provide any custom context for dump's Data object.
Let's use it
