### ISSUE TITLE
502 on https://buggregator.dev/

### ISSUE THREAD

**Issue by fey** [buggregator/server#189]
https://buggregator.dev/

502 Bad Gateway
nginx/1.18.0 (Ubuntu)

![image](https://github.com/buggregator/server/assets/697178/35ac8ec9-c2eb-467e-a7ed-1d2e997ee67f)

https://downforeveryoneorjustme.com/buggregator.dev?proto=https

![image](https://github.com/buggregator/server/assets/697178/d90895c8-d362-48d0-b055-aecde650f0d8)

**Comment by butschster** [comment]
Thx!

**Comment by butschster** [comment]
У нас есть телеграм https://t.me/spiralphp/15, можно там писать и обсуждать в том числе такие вещи
