### ISSUE TITLE
Error:  in \/app\/app\/src\/Application\/Domain\/Entity\/Json.php on line 23

### ISSUE THREAD

**Issue by CasaMare** [buggregator/server#194]
Unable to typecast the payload field. App\\Application\\Domain\\Entity\\Json::__construct(): Argument #1 ($data) must be of type JsonSerializable|array, null given, called in \/app\/app\/src\/Application\/Domain\/Entity\/Json.php on line 23

Problem with json decode 
Example :  var_dump(json_decode('null'));

**Comment by butschster** [comment]
Thx @CasaMare!
