### ISSUE TITLE
SMTP duplicating events

### ISSUE THREAD

**Issue by CasaMare** [buggregator/server#212]
in version 1.10.0 still exist this problem 
https://github.com/buggregator/server/issues/74

I am trying to send 3 different emails at the same time but in buggregator i see/receive 3 identical

**Comment by butschster** [comment]
Could you provide more details about your application? 
- Framework
- web server
- smtp client

**Comment by CasaMare** [comment]
-Laravel v9
-nginx, but laravel in docker
-symfony/mailer
