### ISSUE TITLE
MimeType for attachments: MySQL write error

### ISSUE THREAD

**Issue by TimMoor** [buggregator/server#224]
See: [https://github.com/guzzle/psr7/blob/2.7/src/MimeType.php](https://github.com/guzzle/psr7/blob/2.7/src/MimeType.php)

And the 32 size limit for 'mime' in: 20240503.065730_0_0_default_create_smtp_attachments.php

Getting the exception when handling xls attachments:

buggregator    | 2024-07-18T12:22:14+0000	ERROR	app         	Cycle\Database\Exception\StatementException: SQLSTATE[HY000]: General error: 1105 string 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' is too large for column 'mime' in /app/vendor/cycle/database/src/Driver/MySQL/MySQLDriver.php at line 60 [] []

**Comment by CasaMare** [comment]
https://github.com/buggregator/server/pull/225
