### ISSUE TITLE
Bug: MySQl error and because of that I can not seem to use Bugregator

### ISSUE THREAD

**Issue by peaklabs-dev** [buggregator/server#237]
Error:
```
2024-08-11T17:36:26+0000	ERROR	app         	Cycle\Database\Exception\StatementException: There is already an active transaction in /app/vendor/cycle/database/src/Driver/MySQL/MySQLDriver.php at line 60 [] []
````
Reproduction:
Install coolify locally and also bugregator. You need to change the ports for the install for example like this:
```bash
docker run -p 9002:8000 -p 2025:1025 -p 10912:9912 -p 10913:9913 ghcr.io/buggregator/server:latest
```

Edit: 13.08.24 Just updated to the latest version. And because of this error I can not use Buggregator.

**Comment by butschster** [comment]
Hey @zachmu,

Not sure why, but since the `1.42.9` release, we've started seeing the error mentioned above.

**Comment by ayntk-ai** [comment]
Amazing work. Now it is working. Thank you so much for fixing the tow bug so fast.
