### ISSUE TITLE
SMTP server stopped working after 1.10.4

### ISSUE THREAD

**Issue by maantje** [buggregator/server#243]
Hey @butschster,

I’ve been experiencing some strange behavior with the newer version of the server. When I send an email to the SMTP server, the process hangs.

This issue started occurring after version ~1.11.0~ 1.10.4. I reviewed the changes since then, and I’m wondering if the modification on this [line](https://github.com/buggregator/server/blob/e6bd03672f0d199a1caa8f0d34233f34ee974a97/app/modules/Smtp/Interfaces/TCP/ResponseMessage.php#L33) could be the culprit.

In older versions, there was always a hardcoded \r\n, but now, for the accepted response, it’s just \r. Since I’m on a Mac, I probably need the \n as well.

~Is there a guide available for setting up a local copy of the server? I’d like to take a closer look.~
I have found the [guide](https://docs.buggregator.dev/cookbook/dev-env.html)

**Comment by butschster** [comment]
Hey, what version do you use?

**Comment by maantje** [comment]
Hey @butschster,

I just tested version 1.11.3, but it also hangs. The application hangs for about a minute and then stops.

Which version are you referring to? The last version that works for me is 1.11.0. Versions 1.11.1, 1.11.2, and 1.11.3 all have the same issue.

**Comment by maantje** [comment]
@butschster, I added a correction: the last version that was working is 1.10.4. Sorry for the confusion.

**Comment by maantje** [comment]
I haven’t been able to get the server working locally on my host yet, but I tried patching version 1.11.3 from within the Docker container, and that seems to have resolved the issue.

https://github.com/user-attachments/assets/a07046f6-4306-4b4d-ae04-b0f0b7b8420c

**Comment by Catvert** [comment]
Hi,

I've got the same issue on my machine with the latest version. I confirm that 1.10.4 is the latest version working for SMTP.
