### ISSUE TITLE
Boolean dumps are displaying the wrong way around

### ISSUE THREAD

**Issue by binaryfire** [buggregator/server#62]
Hi. There seems to be problem with boolean dumps to the dump server. True is displaying as `false` and false is displaying as `true`. For example, this is the Buggregator JSON:

<img width="389" alt="image" src="https://github.com/buggregator/server/assets/5361908/9194fabb-73bd-4a28-89b1-92f7f6817245">

And this is what's displayed:

<img width="889" alt="image" src="https://github.com/buggregator/server/assets/5361908/a0e55c1f-abb9-4dee-9bcf-96cce8ec05b2">

**Comment by butschster** [comment]
I think this issue is related to https://github.com/buggregator/frontend/issues/11
