### ISSUE TITLE
SMTP duplicating events

### ISSUE THREAD

**Issue by FluffyDiscord** [buggregator/server#74]
I seems that the buggregator displays only the first SMTP message and then shows the same one for another message that was send immediately after.

You can see in the image (sorry for the censorship) that first mail recipient is different from the second mail, yet bugregator shows the same. This extends to the email content too.

![image](https://github.com/buggregator/server/assets/10332247/1d4e521e-bd07-4357-aae8-deeed3a35632)

Also the timestamp on the detail doesn't work correctly. It's always showing current time instead of the time the email was sent, or rather received by bugregator

**Comment by butschster** [comment]
Thx for the bug report!

**Comment by butschster** [comment]
Released

**Comment by gordonsumac** [comment]
> Released

I'm still seeing this, having pulled down the latest stable. I'm using Laravel 9. Same as @FluffyDiscord , in that 2 emails are shown, but both the same (including all email content, to address etc.) when there should be different recipients and content.

**Comment by CasaMare** [comment]
this problem is still exist in version 1.10.0
