### ISSUE TITLE
[FR] Make header fixed

### ISSUE THREAD

**Issue by iGrog** [buggregator/server#97]
Make button `Clear events` always visible on the page:
![image](https://github.com/buggregator/server/assets/842588/e64e154e-2211-436f-afad-e29a8da4f5cd)

This feature greatly aids in clearing contents without the need for scrolling back to the top.

**Comment by roxblnfk** [comment]
As far as I understand, there is already an option that does this
![image](https://github.com/buggregator/server/assets/4152481/98436344-6ed7-4cea-a19c-b8bc60fec4a1)

**Comment by iGrog** [comment]
Didn't notice that option. Sorry.
